#!/usr/bin/env python3
r"""Build pipeline: dist/index.html → gzip → inc/camera_index.h

Workflow:
    pnpm build          # Vite outputs dist/index.html (single file)
    python3 convert.py  # gzip → camera_index.h → pio run

For multi-sensor support, place additional HTMLs as:
    web/index_ov3660.html, web/index_ov5640.html
They'll be packed alongside the Vite output.
"""

import gzip, sys
from pathlib import Path

WEB = Path(__file__).resolve().parent
INC = WEB.parent / "inc"
DIST = WEB / "dist"
OUTPUT = INC / "camera_index.h"
BYTES_PER_LINE = 16


def gz_to_c_string(data: bytes) -> str:
    lines = []
    for i in range(0, len(data), BYTES_PER_LINE):
        chunk = data[i : i + BYTES_PER_LINE]
        escaped = "".join(f"\\x{b:02X}" for b in chunk)
        lines.append(f'    "{escaped}"')
    return "\n".join(lines)


def pack(html_path: Path, sensor: str) -> list[str]:
    html = html_path.read_text(encoding="utf-8")
    data = gzip.compress(html.encode("utf-8"), compresslevel=9)
    name = f"index_{sensor}_html_gz"
    return [
        f"// File: {html_path.name}.gz, Size: {len(data)}",
        f"#define {name}_len {len(data)}",
        f"const unsigned char {name}[] =",
        gz_to_c_string(data),
        "    ;\n",
    ]


def main():
    parts = [
        "// Auto-generated by web/convert.py — DO NOT EDIT",
        "// Workflow:  pnpm build → python3 web/convert.py → pio run",
        "",
    ]

    # OV2640 source: dist/index.html (pnpm build output, CSS/JS inlined)
    # Falls back to legacy raw HTML if dist/ not built yet
    vite_dist = DIST / "index.html"
    legacy = WEB / "index_ov2640.html"

    if vite_dist.exists():
        parts.extend(pack(vite_dist, "ov2640"))
    elif legacy.exists():
        parts.extend(pack(legacy, "ov2640"))

    # Extra sensors (raw HTML, not Vite-built)
    for html_file in sorted(WEB.glob("index_ov*.html")):
        sensor = html_file.stem.replace("index_", "")
        if sensor == "ov2640":
            continue
        parts.extend(pack(html_file, sensor))

    INC.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(parts) + "\n", encoding="utf-8")

    # Report
    all_sources = [vite_dist, legacy] + sorted(WEB.glob("index_ov*.html"))
    all_sources = [f for f in all_sources if f.exists()]
    # deduplicate ov2640 (vite dist + legacy)
    seen = set()
    unique = []
    for f in all_sources:
        sensor = f.stem.replace("index_", "")
        if sensor not in seen:
            seen.add(sensor)
            unique.append(f)

    print(f"Wrote {OUTPUT}")
    for f in unique:
        html = f.read_text(encoding="utf-8")
        gz = gzip.compress(html.encode("utf-8"), compresslevel=9)
        print(f"  {f.name} → {len(gz)} bytes gzipped ({len(html)} chars html)")


if __name__ == "__main__":
    main()
