#!/usr/bin/env python3
r"""Convert web/*.html → gzip → inc/camera_index.h

Usage:
    python3 web/convert.py          # process all index_*.html
    python3 web/convert.py ov2640   # process only index_ov2640.html

Output format: \xNN\xNN... escaped string (compact, no runtime decoder needed).
"""

import gzip, sys
from pathlib import Path

WEB = Path(__file__).resolve().parent
INC = WEB.parent / "inc"
OUTPUT = INC / "camera_index.h"
BYTES_PER_LINE = 16  # bytes per source line before wrapping


def gz_to_c_string(data: bytes) -> str:
    """Convert binary gzip data to C escaped string literal, wrapped at BYTES_PER_LINE."""
    lines = []
    for i in range(0, len(data), BYTES_PER_LINE):
        chunk = data[i : i + BYTES_PER_LINE]
        escaped = "".join(f"\\x{b:02X}" for b in chunk)
        lines.append(f'    "{escaped}"')
    return "\n".join(lines)


def main():
    targets = sys.argv[1:] if len(sys.argv) > 1 else None
    html_files = sorted(WEB.glob("index_*.html"))
    if targets:
        html_files = [f for f in html_files if any(t in f.stem for t in targets)]
    if not html_files:
        print(f"No HTML files found in {WEB}/")
        sys.exit(1)

    parts = [
        "// Auto-generated by web/convert.py — DO NOT EDIT",
        "// Edit web/index_*.html then run:  python3 web/convert.py",
        "",
    ]

    for hf in html_files:
        html = hf.read_text(encoding="utf-8")
        data = gzip.compress(html.encode("utf-8"), compresslevel=9)

        sensor = hf.stem.replace("index_", "")
        name = f"index_{sensor}_html_gz"

        parts.append(f"// File: {hf.name}.gz, Size: {len(data)}")
        parts.append(f"#define {name}_len {len(data)}")
        parts.append(f"const unsigned char {name}[] =")
        parts.append(gz_to_c_string(data))
        parts.append("    ;\n")

    INC.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(parts) + "\n", encoding="utf-8")

    print(f"Wrote {OUTPUT}")
    for hf in html_files:
        html = hf.read_text(encoding="utf-8")
        gz = gzip.compress(html.encode("utf-8"), compresslevel=9)
        print(f"  {hf.name} → {len(gz)} bytes gzipped ({len(html)} chars html)")


if __name__ == "__main__":
    main()
